"""Updated name field to NOT NULL

Revision ID: 63a1d0fa1073
Revises: 5b44c73ec952
Create Date: 2024-11-20 13:31:58.411185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63a1d0fa1073'
down_revision = '5b44c73ec952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_splits', schema=None) as batch_op:
        batch_op.drop_column('total_amount')
        batch_op.drop_column('percentage')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('split_type',
               existing_type=mysql.ENUM('EQUAL', 'PERCENTAGE', 'EXACT'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('paid_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('paid_by',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('split_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('EQUAL', 'PERCENTAGE', 'EXACT'),
               existing_nullable=False)

    with op.batch_alter_table('expense_splits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
