"""empty message

Revision ID: bba55209b8ca
Revises: f2c5785f6024
Create Date: 2024-11-11 18:11:03.375582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba55209b8ca'
down_revision = 'f2c5785f6024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_code', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['unique_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('unique_code')

    # ### end Alembic commands ###
