"""Fix ForeignKey in PaymentIntent

Revision ID: de6db82b5000
Revises: fad4797bb6ff
Create Date: 2024-11-25 11:29:19.420887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6db82b5000'
down_revision = 'fad4797bb6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method_types', sa.Text(), nullable=False),
    sa.Column('payment_method_details', sa.Text(), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_intents_payment_intent_id'), ['payment_intent_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_intents_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_intents_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_intents_payment_intent_id'))

    op.drop_table('payment_intents')
    # ### end Alembic commands ###
